#! /bin/sh

INTERNAL_MONITOR="LVDS-1"
EXTERNAL_MONITOR="VGA-1"

pgrep -x sxhkd > /dev/null || sxhkd &
#bspc monitor -d I II III IV V VI VII VIII IX X
if [[ $(xrandr -q | grep "$EXTERNAL_MONITOR connected") ]]; then
        xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
        bspc monitor "$INTERNAL_MONITOR" -d 
        bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9
        xrandr --addmode "$EXTERNAL_MONITOR" "1920x1080_60.00"
        xrandr --output "$EXTERNAL_MONITOR" --mode "1920x1080_60.00" --left-of "$INTERNAL_MONITOR" --output "$INTERNAL_MONITOR" --mode "1366x768"
else
        bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         0
bspc config window_gap          00

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr &
feh --bg-scale ~/wallpapers/5.png &
